// import React from 'react';

const GET_CUSTOMER_INFO_START = 'GET_CUSTOMER_INFO_START';
const GET_CUSTOMER_INFO_SUCCESS = 'GET_CUSTOMER_INFO_SUCCESS';
const GET_CUSTOMER_INFO_FAILURE = 'GET_CUSTOMER_INFO_FAILURE';
const GET_CUSTOMER_PETS = 'GET_CUSTOMER_PETS';
const REGISTER_CUSTOMER_INFO_START = 'REGISTER_CUSTOMER_INFO_START';
const REGISTER_CUSTOMER_INFO_SUCCESS = 'REGISTER_CUSTOMER_INFO_SUCCESS';
const REGISTER_CUSTOMER_INFO_FAILURE = 'REGISTER_CUSTOMER_INFO_FAILURE';

const GET_GROOMER_INFO_START = 'GET_GROOMER_INFO_START';
const GET_GROOMER_INFO_SUCCESS = 'GET_GROOMER_INFO_SUCCESS';
const GET_GROOMER_INFO_FAILURE = 'GET_GROOMER_INFO_FAILURE';
const REGISTER_GROOMER_INFO_START = 'REGISTER_GROOMER_INFO_START';
const REGISTER_GROOMER_INFO_SUCCESS = 'REGISTER_GROOMER_INFO_SUCCESS';
const REGISTER_GROOMER_INFO_FAILURE = 'REGISTER_GROOMER_INFO_FAILURE';

const GET_USER_INFO_START = 'GET_USER_INFO_START';
const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

const UPDATE_CUSTOMER_START = 'UPDATE_CUSTOMER_START';
const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';
const UPDATE_GROOMER_START = 'UPDATE_GROOMER_START';
const UPDATE_GROOMER_SUCCESS = 'UPDATE_GROOMER_SUCCESS';
const UPDATE_GROOMER_FAILURE = 'UPDATE_GROOMER_FAILURE';

const GET_ALL_PETS_START = 'GET_ALL_PETS_START';
const GET_ALL_PETS_SUCCESS = 'GET_ALL_PETS_SUCCESS';
const GET_ALL_PETS_FAILURE = 'GET_ALL_PETS_FAILURE';
const GET_PET_INFO_START = 'GET_PET_INFO_START';
const GET_PET_INFO_SUCCESS = 'GET_PET_INFO_SUCCESS';
const GET_PET_INFO_FAILURE = 'GET_PET_INFO_FAILURE';
const REGISTER_PET_INFO_START = 'REGISTER_PET_INFO_START';
const REGISTER_PET_INFO_SUCCESS = 'REGISTER_PET_INFO_SUCCESS';
const REGISTER_PET_INFO_FAILURE = 'REGISTER_PET_INFO_FAILURE';
const UPDATE_PET_START = 'UPDATE_PET_START';
const UPDATE_PET_SUCCESS = 'UPDATE_PET_SUCCESS';
const UPDATE_PET_FAILURE = 'UPDATE_PET_FAILURE';
const DELETE_PET_START = 'DELETE_PET_START';
const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
const DELETE_PET_FAILURE = 'DELETE_PET_FAILURE';

export {
  GET_CUSTOMER_INFO_START,
  GET_CUSTOMER_INFO_SUCCESS,
  GET_CUSTOMER_INFO_FAILURE,
  GET_CUSTOMER_PETS,
  REGISTER_CUSTOMER_INFO_START,
  REGISTER_CUSTOMER_INFO_SUCCESS,
  REGISTER_CUSTOMER_INFO_FAILURE,
  GET_GROOMER_INFO_START,
  GET_GROOMER_INFO_SUCCESS,
  GET_GROOMER_INFO_FAILURE,
  REGISTER_GROOMER_INFO_START,
  REGISTER_GROOMER_INFO_SUCCESS,
  REGISTER_GROOMER_INFO_FAILURE,
  GET_USER_INFO_START,
  GET_USER_INFO_SUCCESS,
  GET_USER_INFO_FAILURE,
  UPDATE_CUSTOMER_START,
  UPDATE_CUSTOMER_SUCCESS,
  UPDATE_CUSTOMER_FAILURE,
  UPDATE_GROOMER_START,
  UPDATE_GROOMER_SUCCESS,
  UPDATE_GROOMER_FAILURE,
  GET_ALL_PETS_START,
  GET_ALL_PETS_SUCCESS,
  GET_ALL_PETS_FAILURE,
  GET_PET_INFO_START,
  GET_PET_INFO_SUCCESS,
  GET_PET_INFO_FAILURE,
  REGISTER_PET_INFO_START,
  REGISTER_PET_INFO_SUCCESS,
  REGISTER_PET_INFO_FAILURE,
  UPDATE_PET_START,
  UPDATE_PET_SUCCESS,
  UPDATE_PET_FAILURE,
  DELETE_PET_START,
  DELETE_PET_SUCCESS,
  DELETE_PET_FAILURE,
};
